### ISSUE TITLE
Printing QR codes

### ISSUE THREAD

**Issue by Xifiggam** [GustavAT/Votor#6] opened 2018-12-06 10:08 UTC
Upon printing the QR codes with the standard windows print ot pdf I only receive a one side pdf with cut qr codes.
[sfsdfs.pdf](https://github.com/GustavAT/Votor/files/2652612/sfsdfs.pdf)

**Comment by Monomus** [comment] 2018-12-07 22:57
Problem caused by browser default printing margin. Fixed by setting the margin to a fixed value on all browsers.

**Closed as completed by Monomus** 2018-12-07 22:57 UTC
Labels: bug

**Comment by Xifiggam** [comment] 2018-12-10 09:02
Problem is still persisting

[nsdfnsofnsio.pdf](https://github.com/GustavAT/Votor/files/2662356/nsdfnsofnsio.pdf)
